package com.plusemon.hisab.domain.util

object Localization {

    enum class Key {
        APP_NAME,
        TAGLINE,
        TOTAL_BALANCE,
        NET_WORTH,
        EXPENSES_THIS_MONTH,
        INCOME_THIS_MONTH,
        NET_SAVINGS,
        SAVINGS_RATE,
        RECENT_TRANSACTIONS,
        SEE_ALL,
        MY_ACCOUNTS,
        ADD_ACCOUNT,
        ADD_TRANSACTION,
        ADD_EXPENSE,
        ADD_INCOME,
        TRANSFER,
        EXPENSE_SHORT,
        INCOME_SHORT,
        TRANSFER_SHORT,
        BUDGETS,
        SAVINGS_GOALS,
        DEBTS_LOANS,
        REPORTS,
        SETTINGS,
        MORE,
        SEARCH_PLACEHOLDER,
        FILTER_BY,
        ALL,
        DATE,
        CATEGORY,
        ACCOUNT,
        AMOUNT,
        NOTE,
        FEE,
        RECEIPT,
        SAVE,
        CANCEL,
        DELETE,
        EDIT,
        UNDO,
        CONFIRM_DELETE,
        DELETE_MSG,
        FROM_ACCOUNT,
        TO_ACCOUNT,
        EXCHANGE_RATE,
        MONTHLY_BUDGET,
        OVERALL_BUDGET,
        BUDGET_WARNING,
        BUDGET_EXCEEDED,
        BUDGET_SAFE,
        SPENT,
        REMAINING,
        LIMIT,
        GOAL_NAME,
        TARGET_AMOUNT,
        CURRENT_SAVED,
        TARGET_DATE,
        DEPOSIT,
        WITHDRAW,
        OWED_TO_ME,
        I_OWE,
        PERSON_NAME,
        DUE_DATE,
        SETTLE,
        RECORD_PAYMENT,
        RECURRING_TRANSACTIONS,
        FREQUENCY,
        DAILY,
        WEEKLY,
        MONTHLY,
        PAUSED,
        ACTIVE,
        NATURAL_ENTRY_TITLE,
        NATURAL_ENTRY_HINT,
        NATURAL_ENTRY_SUBMIT,
        SYNCED,
        SYNCING,
        OFFLINE,
        SECURITY,
        PIN_LOCK,
        ENTER_PIN,
        SET_PIN,
        CONFIRM_PIN,
        PIN_INCORRECT,
        HIDE_BALANCES,
        DATA_PORTABILITY,
        EXPORT_CSV,
        EXPORT_SUMMARY,
        IMPORT_CSV,
        DELETE_ACCOUNT,
        DELETE_ACCOUNT_CONFIRM,
        LANGUAGE,
        NUMERAL_SYSTEM,
        CURRENCY,
        DARK_MODE,
        LIGHT_MODE,
        SYSTEM_DEFAULT,
        CHECK_UPDATES,
        SIGN_OUT,
        SIGN_IN_TITLE,
        SIGN_IN_SUBTITLE,
        SIGN_IN_WITH_GOOGLE,
        WELCOME_BACK,
        SIGN_IN_GOOGLE_SUBTITLE,
        FEATURE_SECURE_TITLE,
        FEATURE_SECURE_SUB,
        FEATURE_FAST_TITLE,
        FEATURE_FAST_SUB,
        FEATURE_PRIVACY_TITLE,
        FEATURE_PRIVACY_SUB,
        POWERED_BY_HISAB,
        SIGN_IN_EMAIL,
        SIGN_UP_EMAIL,
        EMAIL,
        PASSWORD,
        NAME,
        CREATE_ACCOUNT,
        ALREADY_HAVE_ACCOUNT,
        DONT_HAVE_ACCOUNT,
        ERROR_EMPTY_FIELDS,
        ERROR_INVALID_EMAIL,
        ERROR_WRONG_PASSWORD,
        ERROR_USER_NOT_FOUND,
        ERROR_USER_EXISTS,
        ERROR_NETWORK,
        ERROR_AUTH_CANCELLED,
        ERROR_UNKNOWN,
        EMPTY_TRANSACTIONS,
        EMPTY_ACCOUNTS,
        EMPTY_BUDGETS,
        EMPTY_GOALS,
        EMPTY_DEBTS,
        ARCHIVED_ACCOUNTS,
        ARCHIVED_ACCOUNTS_SUBTITLE,
        UNARCHIVE,
        ARCHIVED_BADGE,
        NO_ARCHIVED_ACCOUNTS,
        INSIGHT_TITLE,
        INSIGHT_SPENT_MORE,
        INSIGHT_SPENT_LESS,
        INSIGHT_TOP_EXPENSE,
        INSIGHT_SAVINGS_GREAT,
        INSIGHT_BUDGET_ALERT
    }

    private val bnMap: Map<Key, String> = mapOf(
        Key.APP_NAME to "হিসাব",
        Key.TAGLINE to "দৈনিক আয়-ব্যয় ও অর্থ ব্যবস্থাপনা",
        Key.TOTAL_BALANCE to "মোট ব্যালেন্স",
        Key.NET_WORTH to "মোট সম্পদ",
        Key.EXPENSES_THIS_MONTH to "চলতি মাসের খরচ",
        Key.INCOME_THIS_MONTH to "চলতি মাসের আয়",
        Key.NET_SAVINGS to "নিট সঞ্চয়",
        Key.SAVINGS_RATE to "সঞ্চয়ের হার",
        Key.RECENT_TRANSACTIONS to "সাম্প্রতিক লেনদেন",
        Key.SEE_ALL to "সব দেখুন",
        Key.MY_ACCOUNTS to "আমার অ্যাকাউন্টসমূহ",
        Key.ADD_ACCOUNT to "অ্যাকাউন্ট যোগ করুন",
        Key.ADD_TRANSACTION to "লেনদেন যোগ করুন",
        Key.ADD_EXPENSE to "খরচ লিখুন",
        Key.ADD_INCOME to "আয় যোগ করুন",
        Key.TRANSFER to "টাকা স্থানান্তর",
        Key.EXPENSE_SHORT to "খরচ",
        Key.INCOME_SHORT to "আয়",
        Key.TRANSFER_SHORT to "স্থানান্তর",
        Key.BUDGETS to "বাজেট",
        Key.SAVINGS_GOALS to "সঞ্চয় লক্ষ্য",
        Key.DEBTS_LOANS to "দেনা-পাওনা",
        Key.REPORTS to "রিপোর্ট",
        Key.SETTINGS to "সেটিংস",
        Key.MORE to "অন্যান্য",
        Key.SEARCH_PLACEHOLDER to "লেনদেন খুঁজুন (বিবরণ, টাকা...)",
        Key.FILTER_BY to "ফিল্টার করুন",
        Key.ALL to "সব",
        Key.DATE to "তারিখ",
        Key.CATEGORY to "ক্যাটাগরি",
        Key.ACCOUNT to "অ্যাকাউন্ট",
        Key.AMOUNT to "টাকার পরিমাণ",
        Key.NOTE to "মন্তব্য / নোট",
        Key.FEE to "চার্জ / ফি",
        Key.RECEIPT to "রসিদ / ছবি",
        Key.SAVE to "সংরক্ষণ করুন",
        Key.CANCEL to "বাতিল",
        Key.DELETE to "মুছুন",
        Key.EDIT to "সম্পাদনা",
        Key.UNDO to "পূর্বাবস্থায় আনুন",
        Key.CONFIRM_DELETE to "মুছে ফেলতে চান?",
        Key.DELETE_MSG to "এই তথ্যটি মুছে ফেলা হবে। আপনি কি নিশ্চিত?",
        Key.FROM_ACCOUNT to "উৎস অ্যাকাউন্ট",
        Key.TO_ACCOUNT to "গন্তব্য অ্যাকাউন্ট",
        Key.EXCHANGE_RATE to "বিনিময় হার",
        Key.MONTHLY_BUDGET to "মাসিক বাজেট",
        Key.OVERALL_BUDGET to "মোট মাসিক বাজেট",
        Key.BUDGET_WARNING to "সতর্কতা: বাজেটের ৭০% এর বেশি খরচ হয়েছে!",
        Key.BUDGET_EXCEEDED to "বাজেট অতিক্রম করেছে!",
        Key.BUDGET_SAFE to "বাজেটের মধ্যেই আছে",
        Key.SPENT to "খরচ হয়েছে",
        Key.REMAINING to "অবশিষ্ট আছে",
        Key.LIMIT to "সর্বোচ্চ সীমা",
        Key.GOAL_NAME to "লক্ষ্যের নাম",
        Key.TARGET_AMOUNT to "লক্ষ্যের পরিমাণ",
        Key.CURRENT_SAVED to "বর্তমান সঞ্চয়",
        Key.TARGET_DATE to "শেষ তারিখ",
        Key.DEPOSIT to "জমা করুন",
        Key.WITHDRAW to "উত্তোলন",
        Key.OWED_TO_ME to "পাওনা (আমাকে দেবে)",
        Key.I_OWE to "দেনা (আমি দেব)",
        Key.PERSON_NAME to "ব্যক্তির নাম",
        Key.DUE_DATE to "পরিশোধের তারিখ",
        Key.SETTLE to "পরিশোধ সম্পন্ন",
        Key.RECORD_PAYMENT to "টাকা পরিশোধ লিখুন",
        Key.RECURRING_TRANSACTIONS to "স্বয়ংক্রিয় পুনরাবৃত্ত লেনদেন",
        Key.FREQUENCY to "পুনরাবৃত্তির সময়",
        Key.DAILY to "দৈনিক",
        Key.WEEKLY to "সাপ্তাহিক",
        Key.MONTHLY to "মাসিক",
        Key.PAUSED to "স্থগিত",
        Key.ACTIVE to "চলমান",
        Key.NATURAL_ENTRY_TITLE to "সহজ ভাষায় দ্রুত হিসাব লিখুন",
        Key.NATURAL_ENTRY_HINT to "যেমন: বাজার ১২০০ বিকাশ অথবা lunch 250 cash",
        Key.NATURAL_ENTRY_SUBMIT to "হিসাব যুক্ত করুন",
        Key.SYNCED to "সিঙ্ক সম্পন্ন",
        Key.SYNCING to "সিঙ্ক হচ্ছে...",
        Key.OFFLINE to "অফলাইন মোড",
        Key.SECURITY to "নিরাপত্তা ও লক",
        Key.PIN_LOCK to "পিন কোড সুরক্ষা",
        Key.ENTER_PIN to "৪ ডিজিটের পিন দিন",
        Key.SET_PIN to "নতুন পিন কোড সেট করুন",
        Key.CONFIRM_PIN to "পিন পুনরায় দিন",
        Key.PIN_INCORRECT to "ভুল পিন কোড!",
        Key.HIDE_BALANCES to "ব্যালেন্স লুকান (প্রাইভেসি)",
        Key.DATA_PORTABILITY to "ব্যাকআপ ও ডাটা এক্সপোর্ট",
        Key.EXPORT_CSV to "CSV ফাইলে এক্সপোর্ট করুন",
        Key.EXPORT_SUMMARY to "আর্থিক সারাংশ কপি করুন",
        Key.IMPORT_CSV to "CSV ফাইল থেকে ইমপোর্ট করুন",
        Key.DELETE_ACCOUNT to "অ্যাকাউন্ট ডিলিট করুন",
        Key.DELETE_ACCOUNT_CONFIRM to "আপনার সব তথ্য স্থায়ীভাবে মুছে ফেলা হবে। আপনি কি নিশ্চিত?",
        Key.LANGUAGE to "ভাষা",
        Key.NUMERAL_SYSTEM to "সংখ্যার ধরণ",
        Key.CURRENCY to "মুদ্রা",
        Key.DARK_MODE to "ডার্ক মোড",
        Key.LIGHT_MODE to "লাইট মোড",
        Key.SYSTEM_DEFAULT to "সিস্টেম ডিফল্ট",
        Key.CHECK_UPDATES to "নতুন আপডেট চেক করুন",
        Key.SIGN_OUT to "লগআউট করুন",
        Key.SIGN_IN_TITLE to "হিসাব-এ স্বাগতম",
        Key.SIGN_IN_SUBTITLE to "আপনার আর্থিক হিসাব নিরাপদ ও সহজে রাখুন",
        Key.SIGN_IN_WITH_GOOGLE to "Google দিয়ে এগিয়ে যান",
        Key.WELCOME_BACK to "আবারও স্বাগতম 👋",
        Key.SIGN_IN_GOOGLE_SUBTITLE to "চালিয়ে যেতে আপনার Google একাউন্ট দিয়ে সাইন ইন করুন",
        Key.FEATURE_SECURE_TITLE to "সুরক্ষিত ও",
        Key.FEATURE_SECURE_SUB to "গোপনীয়",
        Key.FEATURE_FAST_TITLE to "দ্রুত",
        Key.FEATURE_FAST_SUB to "অ্যাক্সেস",
        Key.FEATURE_PRIVACY_TITLE to "আপনার তথ্য",
        Key.FEATURE_PRIVACY_SUB to "আপনারই কাছে",
        Key.POWERED_BY_HISAB to "Powered by Hisab",
        Key.SIGN_IN_EMAIL to "ইমেইল ও পাসওয়ার্ড দিয়ে লগইন",
        Key.SIGN_UP_EMAIL to "নতুন অ্যাকাউন্ট তৈরি করুন",
        Key.EMAIL to "ইমেইল অ্যাড্রেস",
        Key.PASSWORD to "পাসওয়ার্ড",
        Key.NAME to "আপনার নাম",
        Key.CREATE_ACCOUNT to "অ্যাকাউন্ট তৈরি করুন",
        Key.ALREADY_HAVE_ACCOUNT to "আগে থেকেই অ্যাকাউন্ট আছে? লগইন করুন",
        Key.DONT_HAVE_ACCOUNT to "নতুন ব্যবহারকারী? অ্যাকাউন্ট খুলুন",
        Key.ERROR_EMPTY_FIELDS to "অনুগ্রহ করে সব তথ্য পূরণ করুন",
        Key.ERROR_INVALID_EMAIL to "সঠিক ইমেইল দিন",
        Key.ERROR_WRONG_PASSWORD to "ভুল পাসওয়ার্ড দেওয়া হয়েছে",
        Key.ERROR_USER_NOT_FOUND to "এই ইমেইলে কোনো অ্যাকাউন্ট পাওয়া যায়নি",
        Key.ERROR_USER_EXISTS to "এই ইমেইল দিয়ে ইতিমধ্যে অ্যাকাউন্ট তৈরি আছে",
        Key.ERROR_NETWORK to "ইন্টারনেট সংযোগে ত্রুটি দেখা দিয়েছে",
        Key.ERROR_AUTH_CANCELLED to "সাইন-ইন প্রক্রিয়া বাতিল করা হয়েছে",
        Key.ERROR_UNKNOWN to "একটি ত্রুটি হয়েছে। আবার চেষ্টা করুন।",
        Key.EMPTY_TRANSACTIONS to "এখনো কোনো লেনদেন যুক্ত করা হয়নি",
        Key.EMPTY_ACCOUNTS to "কোনো অ্যাকাউন্ট যোগ করা হয়নি",
        Key.EMPTY_BUDGETS to "কোনো বাজেট নির্ধারণ করা হয়নি",
        Key.EMPTY_GOALS to "কোনো সঞ্চয় লক্ষ্য যুক্ত করা হয়নি",
        Key.EMPTY_DEBTS to "কোনো দেনা-পাওনার হিসাব নেই",
        Key.ARCHIVED_ACCOUNTS to "আর্কাইভ করা অ্যাকাউন্ট",
        Key.ARCHIVED_ACCOUNTS_SUBTITLE to "ট্যাপ করে দেখুন বা পুনরুদ্ধার করুন",
        Key.UNARCHIVE to "পুনরুদ্ধার করুন",
        Key.ARCHIVED_BADGE to "আর্কাইভড",
        Key.NO_ARCHIVED_ACCOUNTS to "কোনো আর্কাইভ করা অ্যাকাউন্ট নেই",
        Key.INSIGHT_TITLE to "স্মার্ট হিসাব পরামর্শ",
        Key.INSIGHT_SPENT_MORE to "গত মাসের চেয়ে এ মাসে খরচ বেশি হয়েছে!",
        Key.INSIGHT_SPENT_LESS to "অভিনন্দন! গত মাসের তুলনায় খরচ কমেছে।",
        Key.INSIGHT_TOP_EXPENSE to "এই মাসের প্রধান খরচের খাত:",
        Key.INSIGHT_SAVINGS_GREAT to "আপনি আপনার মাসিক সঞ্চয় লক্ষ্যের দিকে এগিয়ে যাচ্ছেন!",
        Key.INSIGHT_BUDGET_ALERT to "বাজেট নিয়ন্ত্রণের জন্য জরুরি মনোযোগ প্রয়োজন।"
    )

    private val enMap: Map<Key, String> = mapOf(
        Key.APP_NAME to "Hisab",
        Key.TAGLINE to "Daily Expense & Money Manager",
        Key.TOTAL_BALANCE to "Total Balance",
        Key.NET_WORTH to "Net Worth",
        Key.EXPENSES_THIS_MONTH to "Expenses This Month",
        Key.INCOME_THIS_MONTH to "Income This Month",
        Key.NET_SAVINGS to "Net Savings",
        Key.SAVINGS_RATE to "Savings Rate",
        Key.RECENT_TRANSACTIONS to "Recent Transactions",
        Key.SEE_ALL to "See All",
        Key.MY_ACCOUNTS to "My Accounts",
        Key.ADD_ACCOUNT to "Add Account",
        Key.ADD_TRANSACTION to "Add Transaction",
        Key.ADD_EXPENSE to "Add Expense",
        Key.ADD_INCOME to "Add Income",
        Key.TRANSFER to "Transfer Money",
        Key.EXPENSE_SHORT to "Expense",
        Key.INCOME_SHORT to "Income",
        Key.TRANSFER_SHORT to "Transfer",
        Key.BUDGETS to "Budgets",
        Key.SAVINGS_GOALS to "Savings Goals",
        Key.DEBTS_LOANS to "Debts & Loans",
        Key.REPORTS to "Reports",
        Key.SETTINGS to "Settings",
        Key.MORE to "More",
        Key.SEARCH_PLACEHOLDER to "Search transactions (note, amount...)",
        Key.FILTER_BY to "Filter by",
        Key.ALL to "All",
        Key.DATE to "Date",
        Key.CATEGORY to "Category",
        Key.ACCOUNT to "Account",
        Key.AMOUNT to "Amount",
        Key.NOTE to "Note",
        Key.FEE to "Fee / Charge",
        Key.RECEIPT to "Receipt / Image",
        Key.SAVE to "Save",
        Key.CANCEL to "Cancel",
        Key.DELETE to "Delete",
        Key.EDIT to "Edit",
        Key.UNDO to "Undo",
        Key.CONFIRM_DELETE to "Confirm Delete?",
        Key.DELETE_MSG to "This item will be deleted. Are you sure?",
        Key.FROM_ACCOUNT to "From Account",
        Key.TO_ACCOUNT to "To Account",
        Key.EXCHANGE_RATE to "Exchange Rate",
        Key.MONTHLY_BUDGET to "Monthly Budget",
        Key.OVERALL_BUDGET to "Overall Monthly Budget",
        Key.BUDGET_WARNING to "Warning: Over 70% of budget spent!",
        Key.BUDGET_EXCEEDED to "Budget Exceeded!",
        Key.BUDGET_SAFE to "Within Budget",
        Key.SPENT to "Spent",
        Key.REMAINING to "Remaining",
        Key.LIMIT to "Limit",
        Key.GOAL_NAME to "Goal Name",
        Key.TARGET_AMOUNT to "Target Amount",
        Key.CURRENT_SAVED to "Current Saved",
        Key.TARGET_DATE to "Target Date",
        Key.DEPOSIT to "Deposit",
        Key.WITHDRAW to "Withdraw",
        Key.OWED_TO_ME to "Owed to Me",
        Key.I_OWE to "I Owe",
        Key.PERSON_NAME to "Person's Name",
        Key.DUE_DATE to "Due Date",
        Key.SETTLE to "Settle",
        Key.RECORD_PAYMENT to "Record Payment",
        Key.RECURRING_TRANSACTIONS to "Recurring Transactions",
        Key.FREQUENCY to "Frequency",
        Key.DAILY to "Daily",
        Key.WEEKLY to "Weekly",
        Key.MONTHLY to "Monthly",
        Key.PAUSED to "Paused",
        Key.ACTIVE to "Active",
        Key.NATURAL_ENTRY_TITLE to "Quick Natural Language Entry",
        Key.NATURAL_ENTRY_HINT to "e.g. lunch 250 cash or groceries 1200 bkash",
        Key.NATURAL_ENTRY_SUBMIT to "Add Entry",
        Key.SYNCED to "Synced",
        Key.SYNCING to "Syncing...",
        Key.OFFLINE to "Offline",
        Key.SECURITY to "Security & Lock",
        Key.PIN_LOCK to "PIN Code Protection",
        Key.ENTER_PIN to "Enter 4-Digit PIN",
        Key.SET_PIN to "Set 4-Digit PIN",
        Key.CONFIRM_PIN to "Confirm PIN",
        Key.PIN_INCORRECT to "Incorrect PIN code!",
        Key.HIDE_BALANCES to "Hide Balances (Privacy)",
        Key.DATA_PORTABILITY to "Data & Export",
        Key.EXPORT_CSV to "Export to CSV",
        Key.EXPORT_SUMMARY to "Copy Financial Summary",
        Key.IMPORT_CSV to "Import from CSV",
        Key.DELETE_ACCOUNT to "Delete Account & Data",
        Key.DELETE_ACCOUNT_CONFIRM to "All your data will be permanently removed. Are you sure?",
        Key.LANGUAGE to "Language",
        Key.NUMERAL_SYSTEM to "Numeral System",
        Key.CURRENCY to "Currency",
        Key.DARK_MODE to "Dark Mode",
        Key.LIGHT_MODE to "Light Mode",
        Key.SYSTEM_DEFAULT to "System Default",
        Key.CHECK_UPDATES to "Check for Updates",
        Key.SIGN_OUT to "Sign Out",
        Key.SIGN_IN_TITLE to "Welcome to Hisab",
        Key.SIGN_IN_SUBTITLE to "Simple, powerful daily money management",
        Key.SIGN_IN_WITH_GOOGLE to "Continue with Google",
        Key.WELCOME_BACK to "Welcome Back 👋",
        Key.SIGN_IN_GOOGLE_SUBTITLE to "Sign in with your Google account to continue",
        Key.FEATURE_SECURE_TITLE to "Secure &",
        Key.FEATURE_SECURE_SUB to "Private",
        Key.FEATURE_FAST_TITLE to "Fast",
        Key.FEATURE_FAST_SUB to "Access",
        Key.FEATURE_PRIVACY_TITLE to "Your Data",
        Key.FEATURE_PRIVACY_SUB to "Stays Yours",
        Key.POWERED_BY_HISAB to "Powered by Hisab",
        Key.SIGN_IN_EMAIL to "Sign In with Email",
        Key.SIGN_UP_EMAIL to "Create New Account",
        Key.EMAIL to "Email Address",
        Key.PASSWORD to "Password",
        Key.NAME to "Your Name",
        Key.CREATE_ACCOUNT to "Create Account",
        Key.ALREADY_HAVE_ACCOUNT to "Already have an account? Sign In",
        Key.DONT_HAVE_ACCOUNT to "New to Hisab? Create Account",
        Key.ERROR_EMPTY_FIELDS to "Please fill in all required fields",
        Key.ERROR_INVALID_EMAIL to "Please enter a valid email address",
        Key.ERROR_WRONG_PASSWORD to "Incorrect password",
        Key.ERROR_USER_NOT_FOUND to "No account found with this email",
        Key.ERROR_USER_EXISTS to "An account with this email already exists",
        Key.ERROR_NETWORK to "Network connection error",
        Key.ERROR_AUTH_CANCELLED to "Sign-in was cancelled",
        Key.ERROR_UNKNOWN to "An error occurred. Please try again.",
        Key.EMPTY_TRANSACTIONS to "No transactions recorded yet",
        Key.EMPTY_ACCOUNTS to "No accounts found",
        Key.EMPTY_BUDGETS to "No budgets configured yet",
        Key.EMPTY_GOALS to "No savings goals added yet",
        Key.EMPTY_DEBTS to "No debts or loans recorded",
        Key.ARCHIVED_ACCOUNTS to "Archived Accounts",
        Key.ARCHIVED_ACCOUNTS_SUBTITLE to "Tap to view or restore",
        Key.UNARCHIVE to "Restore",
        Key.ARCHIVED_BADGE to "Archived",
        Key.NO_ARCHIVED_ACCOUNTS to "No archived accounts",
        Key.INSIGHT_TITLE to "Smart Spending Insights",
        Key.INSIGHT_SPENT_MORE to "Expenses increased compared to last month!",
        Key.INSIGHT_SPENT_LESS to "Great job! You spent less than last month.",
        Key.INSIGHT_TOP_EXPENSE to "Top expense category this month:",
        Key.INSIGHT_SAVINGS_GREAT to "You are on track with your savings goals!",
        Key.INSIGHT_BUDGET_ALERT to "Some categories need budget attention."
    )

    fun getString(key: Key, isBangla: Boolean): String {
        return if (isBangla) {
            bnMap[key] ?: enMap[key] ?: key.name
        } else {
            enMap[key] ?: bnMap[key] ?: key.name
        }
    }
}
